### ISSUE TITLE
Low bandwidth v2.0.0-beta.13, v2.0.0-beta.14

### ISSUE THREAD

**Issue by PNixx** [amphp/byte-stream#103]
I use [Ridge V2](https://github.com/PNixx/ridge/tree/v2) for RabbitMQ.
When I upgrade the package from version 12 to version v2.0.0-beta.14, message processing on the production server is greatly reduced (see point 1 in the figure). When I return version v2.0.0-beta.12 (see point 2 in the figure), the processing speed returns to the required value.
<img width="437" alt="Снимок экрана 2022-12-28 в 16 12 56" src="https://user-images.githubusercontent.com/1117351/209817972-f359a80c-f2bd-4ea0-b805-517c9b5517e9.png">

**Comment by Bilge** [comment]
What about beta 13?

**Comment by Bilge** [comment]
If it is actually caused by beta 13, [these are the changes](https://github.com/amphp/byte-stream/compare/v2.0.0-beta.12...v2.0.0-beta.13). It seems that readable streams are now allowed to defer to other operations mid-stream. This shouldn't be an issue unless there are other things happening in your process besides reading and those things consume 100% of the CPU load or are synchronous.

**Comment by PNixx** [comment]
There are a lot of requests to PostgreSQL, HTTP requests, and PHPMailer calls via `amphp/parallel` are also used. The code does not use blocking threads. The thread limit in RabbitMQ is set to 20 per worker. CPU load is not more than 80%.

**Comment by trowski** [comment]
I think this may be due to optimization to avoid latency between a few reads in a row introduced in beta 13. Can you please try `v2.x-dev` (current `2.x` branch) to see if https://github.com/amphp/byte-stream/commit/b5a09a3abd7a638ca4cadcf0876ce0ccd8d911d3 fixes the issue?

**Comment by kelunik** [comment]
@PNixx I can't reproduce any such behavior with the examples, so it'd be really helpful to hear your feedback for the commit mentioned above. Did you also update any other libraries?

**Comment by PNixx** [comment]
Checked on v2.0.0 - all works correctly

**Comment by kelunik** [comment]
@PNixx Thanks for confirming!

**Comment by PNixx** [comment]
After the update, I periodically catch errors in various microservices:
```
Uncaught Exception: Fiber stack protect failed: mprotect failed: Cannot allocate memory (12) in /home/shared/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php:479
Stack trace:
#0 /home/shared/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(479): Fiber->start()
#1 /home/shared/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php(533): Revolt\EventLoop\Internal\AbstractDriver->invokeCallbacks()
```

**Comment by PNixx** [comment]
I think the problems started after adding repeat reading https://github.com/amphp/byte-stream/compare/v2.0.0-beta.12...v2.0.0-beta.13

**Comment by PNixx** [comment]
@kelunik Very unstable code behavior. I had to downgrade the following packages:
amphp/byte-stream: v2.0.0-beta.12
amphp/socket: v2.0.0-beta.7
amphp/dns: v2.0.0-beta.5
amphp/http-client: v5.0.0-beta.6
On the specified versions, the most stable and fastest processing.
