### ISSUE TITLE
Drop Buffer

### ISSUE THREAD

**Issue by kelunik** [amphp/byte-stream#13]
I hereby propose to drop `Buffer`. As far as I'm aware there's not a single use of it in your libraries. It will be kept in the history and can be restored if need arises.

It can stay if somebody is willing to write tests for it, but I'm currently not, and I don't want to have it here without any tests.

**Comment by trowski** [comment]
Yep, fine by me. I used it mainly for prototyping, but then would drop it and use raw string ops.
