### ISSUE TITLE
Use ClosedError instead of ClosedException

### ISSUE THREAD

**Issue by bwoebi** [amphp/byte-stream#17]
It's clearly an Error, as it only occurs if you explicitly closed a stream and then still try to operate on it.

(Please fix in the next major to be released.)

**Comment by kelunik** [comment]
@bwoebi In fact this is not true. While it is true for file handles, it is not true for TCP streams.

**Comment by bwoebi** [comment]
I thought on TCP streams, we just resolve with `null` if the stream is externally closed?!

**Comment by kelunik** [comment]
@bwoebi For reading, yes, but not for writing.

**Comment by kelunik** [comment]
@bwoebi Can I close this one? I don't think we need `ClosedException` _and_ `ClosedError`.

**Comment by bwoebi** [comment]
We do need it. The one you may want to catch, the other most definitely not.

**Comment by kelunik** [comment]
I vote to close this. Writing to a closed peer might totally happen if you have a writing coroutine and close the stream from somewhere else, e.g. the reading coroutine. Having to add an extra flag or catching `ClosedError` is just horrible.
