### ISSUE TITLE
100% CPU with PHP built-in streams

### ISSUE THREAD

**Issue by kelunik** [amphp/byte-stream#21]
`php://temp` and `php://memory` streams result in 100% CPU usage. It's probably due to them not being actual streams that can be used with `stream_select`, so there should probably be a test for that.

https://gist.github.com/umbri/2a3e558d487b5e6756768547e660f95a

```php
<?php

use Amp\ByteStream\ResourceInputStream;
use Amp\ByteStream\ResourceOutputStream;
use Amp\Loop;

require_once __DIR__ . "/../vendor/autoload.php";

Loop::run(function () {
    $memory = fopen("php://temp", "r+");

    $stdin = new ResourceInputStream($memory);
    $stdout = new ResourceOutputStream($memory);

    Loop::delay(1000, function () use ($stdout) {
        echo "write" . PHP_EOL;

        $stdout->write("Hello, World!");
    });

    while (($chunk = yield $stdin->read()) !== null) {
        echo "data -> $chunk" . PHP_EOL;
    }
});
```

**Comment by bwoebi** [comment]
Not sure whether this is the right place. Shouldn't it be asserted within the amp Loop directly?

Also, this is not a bug, it's a feature request to explicitly reject invalid inputs.

**Comment by kelunik** [comment]
Not rejecting invalid inputs is definitely a bug, not a feature. Amp itself could also just check for that, yes.

**Comment by bwoebi** [comment]
It is a feature as we cannot possibly know all inputs we want to reject. Extensions may provide inputs which happen to be castable to a file descriptor. PHP does not expose the file descriptor cast directly to userland, so it's a feature request to reject _specific_ invalid inputs.

**Comment by bwoebi** [comment]
I do think that we should though explicitly mark behavior as _unspecified_ in case we do not explicitly know that we support it. (create a list of what's officially supported)

In that case you may get any behavior from 100% CPU to segfault or simple exception.

E.g. NativeLoop is able to support more types of file descriptors than UvLoop for example. e.g. you could pass the resource probe returned by inotify_init() to NativeLoop, but not Uv. But we cannot possibly know all cases we do support.

**Comment by kelunik** [comment]
https://github.com/amphp/byte-stream/pull/24 solved this, too.
