### ISSUE TITLE
Remove length requirement for write promises

### ISSUE THREAD

**Issue by kelunik** [amphp/byte-stream#22]
Currently we resolve promises from `write` to the length written. I think we can remove that. That'd allow an optimization like using a singleton `NullSuccess` object.

**Comment by trowski** [comment]
The interface doesn't explicitly say that the promise is resolved with the length and I think some classes implementing the interface already resolve with null, so I see no problem here.

**Comment by kelunik** [comment]
Closing, as the interface doesn't require anything like that.
