### ISSUE TITLE
feof(): supplied resource is not a valid stream resource

### ISSUE THREAD

**Issue by kelunik** [amphp/byte-stream#32]
```
kelunik@kelunik ❯ ~/GitHub/amphp/artax ❯ 10:24:18 ❯ master
$ php examples/1-get-request.php
HTTP/1.1 200 OK

{
  "user-agent": "Mozilla/5.0 (compatible; Artax)"
}

PHP Warning:  feof(): supplied resource is not a valid stream resource in /home/kelunik/GitHub/amphp/artax/vendor/amphp/byte-stream/lib/ResourceInputStream.php on line 60
```

I guess we can just suppress that one?

**Comment by rdlowrey** [comment]
I usually prefer to do an `if (!is_resource($res) || feof($res))` check when testing for liveness...

**Comment by kelunik** [comment]
I'm curious why it happened, it never happened before. And it's not 100% reproducible.

**Comment by kelunik** [comment]
It's really strange. When I put the following code in the line before, it never prints anything, but the warning is still triggered.

```php
if (!\is_resource($stream)) {
    \fwrite(\STDERR, "\n" . $this->trace . "\n\n");
}
```

**Comment by bwoebi** [comment]
Question: is `$data === '' && !feof($res)` _ever_ true? AFAIK, an empty string returned from fread/stream_get_contents should _always_ indicate eof by definiton for layer 4 streams. I'm not sure about tls streams though (as these have overhead not delivered to the reader).

**Comment by bwoebi** [comment]
By the way, I suspect the issue is related to tls streams and won't ever happen with raw layer 4 streams. Am I correct about this?

**Comment by kelunik** [comment]
I'm pretty sure it happens with TLS streams. I'm not sure whether the warning is because of TLS streams. Might also be because of the new process library.

**Comment by kelunik** [comment]
Ignore what I just said about the process library. As there's no new version of `amphp/file` / `amphp/parallel` yet, that isn't even installed by Artax, yet.

**Comment by kelunik** [comment]
This is caused by `amphp/parallel` when `pthreads` is enabled.

```
#0 /home/kelunik/GitHub/amphp/artax/vendor/amphp/parallel/lib/Sync/ChannelledSocket.php:22 Amp\ByteStream\ResourceInputStream->__construct()
#1 /home/kelunik/GitHub/amphp/artax/vendor/amphp/parallel/lib/Threading/Internal/Thread.php:88 Amp\Parallel\Sync\ChannelledSocket->__construct()
#2 /home/kelunik/GitHub/amphp/artax/vendor/amphp/amp/lib/Loop/Driver.php:112 Amp\Parallel\Threading\Internal\Thread->Amp\Parallel\Threading\Internal\{closure}()
#3 /home/kelunik/GitHub/amphp/artax/vendor/amphp/amp/lib/Loop/Driver.php:70 Amp\Loop\Driver->tick()
#4 /home/kelunik/GitHub/amphp/artax/vendor/amphp/amp/lib/Loop.php:76 Amp\Loop\Driver->run()
#5 /home/kelunik/GitHub/amphp/artax/vendor/amphp/parallel/lib/Threading/Internal/Thread.php:99 Amp\Loop::run()
#6 Amp\Parallel\Threading\Internal\Thread->run()
```
