### ISSUE TITLE
feof may hang

### ISSUE THREAD

**Issue by brstgt** [amphp/byte-stream#46]
I encountered hanging `feof` resulting in `StreamException("The stream was closed by the peer")`.
This happens when doing requests in Kubernetes to Facebook.

Omitting the feof check "fixes" it.

A workaround (and better code) would be to not check on `@feof` before the write but setting an error handler for the `fwrite` and cathing warnings and converting them to stream exceptions.

Example:
```
                    $eh = set_error_handler([$this, 'onSocketWriteError']);
                    
                    if ($chunkSize) {
                        $written = \fwrite($stream, $data, $chunkSize);
                    } else {
                        $written = \fwrite($stream, $data);
                    }

                    set_error_handler($eh);
```

**Comment by trowski** [comment]
`fwrite` emits a warning when attempting a write and the buffer is full. I'm not aware of any way to avoid that problem.

Do we need the `feof` check at all? It seems unreliable at best, which is why we started counting empty writes in the first place.

**Comment by brstgt** [comment]
It seems like this works pretty well:

```
            set_error_handler(function ($errno, $msg, $file, $line) {
                // Skip EAGAIN errors
                if (strpos($msg, "errno=11") !== false) {
                    return;
                }
                throw new StreamException("Error writing to stream: $msg ($errno)", $errno);
            });

            try {
                // Use conditional, because PHP doesn't like getting null passed
                if ($this->chunkSize) {
                    $written = \fwrite($this->resource, $data, $this->chunkSize);
                } else {
                    $written = \fwrite($this->resource, $data);
                }
            }
            finally {
                restore_error_handler();
            }
```

**Comment by trowski** [comment]
What happens if you *only* delete the `feof` and don't bother with the error handler? Does it just keep waiting to write then?

**Comment by brstgt** [comment]
There was no error, so it was fine but i guess the proper way should be to handle fwrite errors, shouldn't it?

**Comment by trowski** [comment]
I'm just trying to understand why `feof` hangs, but `fwrite` succeeds. The custom error handler is probably fine. I think EAGAIN writes are uncommon enough that the performance difference will be negligible.

**Comment by trowski** [comment]
Using `strpos("Resource temporarily unavailable")` also work for me. Can I depend on that error message though?

**Comment by brstgt** [comment]
Does it fail also with the error handler?

I get `temporarily unavailable` on Linux but i first thought errno=11 would be safer. It shouldnt be a big deal to have a platform dependent check, right?

**Comment by kelunik** [comment]
Platform dependent checks are always ugly. Error number will be better than message, because these messages can be localized.

**Comment by trowski** [comment]
@brstgt No, it doesn't fail with the error handler.

Maybe we should be looking at why `feof` is hanging on a non-blocking stream.

**Comment by brstgt** [comment]
It hangs like 1 minute until the peer closes the socket (probably). Hang
means that feof is blocking and not returning. But the socket is working.
If the feof is omitted, the request finishes successfully

Am Di., 25. Dez. 2018, 13:22 hat Niklas Keller <notifications@github.com>
geschrieben:

**Comment by kelunik** [comment]
The only thing I recall that might result in hanging are fragmented TLS records (packets), but we have never verified that.

**Comment by kelunik** [comment]
See https://github.com/php/php-src/pull/3729 for a fix.

**Comment by kelunik** [comment]
The latest PHP releases are fixed now.
