### ISSUE TITLE
Immediate reads and writes might result in blocking

### ISSUE THREAD

**Issue by kelunik** [amphp/byte-stream#49]
A tight loop of reading and writing with data always being available and always writable, might result in a blocking loop. We should discuss measures to mitigate that, e.g. scheduling immediate write with a `Loop::defer()` in case many of them happen in a tight loop.

**Comment by trowski** [comment]
Looks like this came up in the past for reading, as we already have [this defer](https://github.com/amphp/byte-stream/blob/master/lib/ResourceInputStream.php#L149-L152) when reading. For writing we can skip attempting the write and always enable the write watcher, which will push queued writes to the next tick.

**Comment by kelunik** [comment]
I think it's fine for now then.
