### ISSUE TITLE
Modify chunk size on the fly

### ISSUE THREAD

**Issue by ostrolucky** [amphp/byte-stream#50]
I would like to change the `chunksize` during `Resouce(Input|Output)Stream` object lifecycle, not just when constructing it. Can we have chunksize mutator, or optional argument in `read`?

**Comment by bwoebi** [comment]
There's no technical reason against introducing a setter for it.

However I am curious what is your use case?

**Comment by ostrolucky** [comment]
This is so program can tweak the chunk size being used based on current r/w speeds

**Comment by bwoebi** [comment]
I strongly doubt it will bring any benefit, but I'm open to seeing actual benchmarks and be told otherwise (i.e. add your own setter for testing and bench it then).

**Comment by ostrolucky** [comment]
In that case having it in constructor would also be questionable, wouldn't it?

**Comment by kelunik** [comment]
I'm fine with a setter there, do you want to provide a PR?

**Comment by ostrolucky** [comment]
Actually I would rather you add it because I don't know some internal details I feel are needed for this. Eg there is static closure being used for watcher that I don't know how am I allowed to approach.
