### ISSUE TITLE
ResourceOutputStream interrupts writing without consumer giving information what was written/unwritten

### ISSUE THREAD

**Issue by ostrolucky** [amphp/byte-stream#51]
I'm dealing with situation that following line https://github.com/amphp/byte-stream/blob/6bbfcb6f47e92577e739586ba0c87e867be70a23/lib/ResourceOutputStream.php#L95 throws exception, but doesn't expose information what was written/what is left to write, which makes it very difficult to handle such situation in case of incomplete chunk write. My aim is handling gracefully such exception and re-writing this data to different stream.

I suggest to create custom exception which carries `$data` it was not succeeded to write.

**Comment by kelunik** [comment]
This won't really help, since you still won't know which data the other and received. Data may have been written to the kernel's buffer but been sent.

**Comment by ostrolucky** [comment]
It will help, I tested that. Just expose what information that class already has.

**Comment by ostrolucky** [comment]
Why was this closed without explanation? 

ResourceOutputStream checks if length of $data equals to value from fwrite. If it doesn't, it repeats the write with unwritten data. If it doesn't succeed, it throws exception. I need to know what it tried to write last time.

**Comment by kelunik** [comment]
I didn't intend to close this, yet. Probably mistyped on my phone.

**Comment by trowski** [comment]
As @kelunik pointed out, how useful is that information? When you write to a socket, you are only receiving confirmation that the OS has room in it's buffer for the data written. There is no guarantee that the client actually received that data.

**Comment by ostrolucky** [comment]
That's all I need. If I don't send this data at all, it's definitely lost. If I do, there is high chance of this data reaching destination. Also not sure why are you talking about socket again, that's not the only resource. Do you have the same viewpoint for eg. files? fwrite returning > 0 not being guarantee for data being written to file? That seems kinda ridiculous to me.

**Comment by kelunik** [comment]
Re-opened, as it has been closed by the merge, but the merged commit has been reverted.

**Comment by kelunik** [comment]
@ostrolucky `ResourceOutputStream` shouldn't be used for files, it just happens to work.

I'm not 100% opposed to exposing the information, but I think it is misleading and will not report what most people expect. I'd be cool to have information from the operating system which data has been ACKed by the receiving party, but we currently don't have that data.

**Comment by kelunik** [comment]
I think it's a better idea to expose the unwritten bytes instead of the written chunk if we choose to expose that information, as with that information you can directly attempt a new write on reconnection or whatever your logic is.

**Comment by ostrolucky** [comment]
That patch reported chunk that didn't succeed to be written. Turning it to int is more complicated from both sides - library and consumer. I need that chunk so I can repeat write.

**Comment by kelunik** [comment]
I'm closing this in favor of https://github.com/amphp/file/issues/35. We don't want to expose this information for every stream in this library, because for sockets it's generally misleading.
