### ISSUE TITLE
LineReader custom delimiter

### ISSUE THREAD

**Issue by userqq** [amphp/byte-stream#69]
Hi. 
It would be great to have possibility use custom delimiters in LineReader, e.g.

```php
final class LineReader
{
    ...
    public function __construct(InputStream $inputStream, $delimiter = "\n")
    ...
}
```
```php
$reader = new \Amp\ByteStream\LineReader($stream, "\x0a\x00");
```

**Comment by kelunik** [comment]
Looks like a useful addition. However, it needs some special consideration for `\rtrim($line, "\r");` which shouldn't be applied in that case. Do you want to provide a PR?

**Comment by userqq** [comment]
@kelunik 
Please see draft PR https://github.com/amphp/byte-stream/pull/77
