### ISSUE TITLE
Make read consistent

### ISSUE THREAD

**Issue by kelunik** [amphp/byte-stream#7]
Reading after the stream has closed should always resolve to `null` instead of throwing an exception.

**Comment by ekinhbayar** [comment]
Shouldn't trying to read a closed stream hint you that you attempted to read closed stream?

**Comment by bwoebi** [comment]
@ekinhbayar only if you want to read a fixed amount of bytes (where you want a guarantee that the returned string is exactly that long) [as opposed to _up to_].
In any other case, a string of size 0 (or null for instance) is not problematic. It's even desirable, as you _expect_ that streams are going to end sometime.

**Comment by kelunik** [comment]
@bwoebi I think @ekinhbayar's point is reading repeatedly from an already closed stream.

@ekinhbayar: Yes, that's probably always a programming error, but it makes implementing some things more complex. It's a trade-off for easier to implement streams.

**Comment by bwoebi** [comment]
I disagree.

There might be e.g. multiple optional parts at stream end, so, when you try to do multiple calls to read until EOL, the optional parts will just end up with null, but that's totally fine.
If it were throwing an exception, that'd need unnecessary extra handling complexity in user side.

**Comment by kelunik** [comment]
> There might be e.g. multiple optional parts at stream end, so, when you try to do multiple calls to read until EOL, the optional parts will just end up with null, but that's totally fine.

I do not understand, could you illustrate with an example?

**Comment by ekinhbayar** [comment]
I can see read returning either Promise or null being desirable. I was thinking in case when you call read multiple times after a stream returned the promise. +1 for an example to see that point clearly, but I understand the preference of null instead of an exception.

**Comment by kelunik** [comment]
@ekinhbayar See https://github.com/amphp/byte-stream/commit/23f5ba91b96773afed87766de5306d22715e99bd for an example with an exception instead of `null` after the first `null`.

The return type is always `Promise`, not `Promise|null`, but the promise resolves to `string|null`.

**Comment by ekinhbayar** [comment]
@kelunik seems I misinterpreted, I see how it is now.

**Comment by kelunik** [comment]
I think this task has been completed. Everything else is a bug.
