### ISSUE TITLE
The url inside the composer.json should be in their secure version?

### ISSUE THREAD

**Issue by S-Tian86** [amphp/byte-stream#87]
Hi,

I think the url should be written with https;// instead of http://.
https://github.com/amphp/byte-stream/blob/77decf18efbabf23e3c35e16946322d6d621fa61/composer.json#L3
What do you think?

Regards

**Comment by kelunik** [comment]
Yes, it should, do you want to send a PR?

**Comment by S-Tian86** [comment]
Sure, no problem
